name: nf-core-genebygenebact-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.6
  - conda-forge::pymdown-extensions=7.1
  - bioconda::fastqc=0.11.9
  - bioconda::fastp=0.20.1
  - bioconda::unicycler=0.4.7
  - bioconda::bandage=0.8.1
  - bioconda::quast=5.0.2
  - bioconda::taranis=2.0.1
  - bioconda::multiqc=1.9
  - bioconda::entrez-direct==13.9
  - requests==2.25.1
