name: nf-core-genebygenebact-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - python>=3.6 ## tiene que ser menor a 3.8 porque si no biopython no funciona
  - bioconda::fastqc=0.11.9 # viralrecon v
  - bioconda::fastp=0.20.1 # viralrecon v
  - bioconda::unicycler=0.4.7 # viralrecon v
  - bioconda::bandage=0.8.1 # viralrecon v
  - bioconda::quast=5.0.2
  - bioconda::multiqc=1.9 # viralrecon v
  - bioconda::blast=2.5
  - bioconda::mash=1.1
  - bioconda::prodigal
  - bioconda::prokka  #(se me ha isntalado 1.12)

  - pip:
    - biopython==1.72
    - pandas
    - progressbar
    - openpyxl
    - plotly
    - numpy
    - requests
    - entrez-direct==13.9
